In [1]:
#!/usr/bin/env python3


import torch
from ontology_scores import *

parameter_model = "1.4B"
step = "step143000"

# save_wordnet_hypernym(parameter_model, step, True)
# mats = get_mats(parameter_model, step, True)

# torch.save(mats[0], f"test1.pt")
# torch.save(mats[1], f"test2.pt")
# torch.save(mats[2], f"test3.pt")

[nltk_data] Downloading package wordnet to /home/raymond/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: read).
Your token has been saved to /home/raymond/.cache/huggingface/token
Login successful


In [2]:
adj = torch.load(f"test1.pt")
cos = torch.load(f"test2.pt")
diff = torch.load(f"test3.pt")

cat_embeddings = torch.load("category_embeddings.pt")       # for work.n.01, the one with nan
cov = torch.load("cov.pt")


print(causal_sep_score(adj, cos))
print(hierarchy_score(diff))

print(True in torch.isnan(cat_embeddings))
print(True in torch.isnan(cov))




nan
nan
False
False


In [3]:
cat_embeddings_list = []
for row in cat_embeddings:
    cat_embeddings_list.append([thing.item() for thing in row])

cov_list = []
for row in cov:
    cov_list.append([thing.item() for thing in row])

In [4]:
for i in range(len(cov)):
    for j in range(i+1, len(cov)):
        norm = torch.norm(cov[i] - cov[j]).item()
        if norm < 0.3:
            print(i, j, norm)

In [5]:
print(torch.linalg.matrix_rank(cat_embeddings))
print(torch.linalg.matrix_rank(cov))

tensor(2048)
tensor(2048)


In [6]:
print(cat_embeddings.shape)
print(cov.shape)

torch.Size([12933, 2048])
torch.Size([2048, 2048])


In [10]:
pseudo_inv = torch.linalg.pinv(cov)
print(pseudo_inv)
print(pseudo_inv.shape)

import numpy as np
pseudo_inv = np.linalg.pinv(cov)
pseudo_inv = torch.tensor(pseudo_inv)
print(pseudo_inv)


from scipy import linalg
pseudo_inv = linalg.pinv(cov)
pseudo_inv = torch.tensor(pseudo_inv)
print(pseudo_inv)

tensor([[ 2.9616, -0.0383, -0.0463,  ..., -0.0529, -0.0385,  0.0750],
        [-0.0383,  3.1854,  0.0676,  ...,  0.0453,  0.1216,  0.1139],
        [-0.0463,  0.0676,  3.0754,  ...,  0.0179, -0.0380, -0.0207],
        ...,
        [-0.0529,  0.0453,  0.0179,  ...,  3.2051, -0.0545, -0.0184],
        [-0.0385,  0.1216, -0.0380,  ..., -0.0545,  3.1916, -0.0605],
        [ 0.0750,  0.1139, -0.0207,  ..., -0.0184, -0.0605,  3.0632]])
torch.Size([2048, 2048])
tensor([[ 2.9616, -0.0383, -0.0463,  ..., -0.0529, -0.0385,  0.0750],
        [-0.0383,  3.1854,  0.0676,  ...,  0.0453,  0.1216,  0.1139],
        [-0.0463,  0.0676,  3.0754,  ...,  0.0179, -0.0380, -0.0207],
        ...,
        [-0.0529,  0.0453,  0.0179,  ...,  3.2051, -0.0545, -0.0184],
        [-0.0385,  0.1216, -0.0380,  ..., -0.0545,  3.1916, -0.0605],
        [ 0.0750,  0.1139, -0.0207,  ..., -0.0184, -0.0605,  3.0632]])
tensor([[ 2.9616, -0.0383, -0.0463,  ..., -0.0529, -0.0385,  0.0750],
        [-0.0383,  3.1854,  0.0676,  